define([
    "specs/framework.js",
    "specs/core/core.helper.js",
    "specs/core/core.module.js",
    "specs/util/helpers/function-helper.js",
    "specs/util/helpers/model-helper.js",
    "specs/util/helpers/storage-helper.js",
    "specs/util/helpers/string-helper.js",
    "specs/util/helpers/uuid-helper.js",
    "specs/util/models/predicate.js"
]);
